<?php namespace JeyKeu\Notify;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-14 at 10:38:00.
 */
class NotifyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Notify
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Notify;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers JeyKeu\Notify\Notify::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JeyKeu\Notify\Notify::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JeyKeu\Notify\Notify::removeAll
     * @todo   Implement testRemoveAll().
     */
    public function testRemoveAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JeyKeu\Notify\Notify::processQueue
     * @todo   Implement testProcessQueue().
     */
    public function testProcessQueue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
