<?php namespace JeyKeu\Notify\Session\Test;

error_reporting(E_ALL & ~E_NOTICE);

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-12 at 02:28:36.
 */
class NotifyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Notify
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \JeyKeu\Notify\Notify(new \JeyKeu\Notify\Session\NativeSession());

        $appSessKey            = 'jeykeu_notify';
        $key                   = 'testKey';
        $value                 = 'testValue';
        $appSessData           = (object) array($key => $value);
        $_SESSION[$appSessKey] = serialize($appSessData);
    }

    public function testAdd()
    {
        $notification = new \JeyKeu\Notify\Notification();
        $notification->setHandle("Persisted-Alert-Notification")
                ->setIsDissmissable(true)
                ->setIsPersisted(true)
                ->setType("alert");
        $this->object->add($notification);
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->object);
        unset($_SESSION);
    }
}
