<?php namespace JeyKeu\Notify\Session\Test;

error_reporting(E_ALL & ~E_NOTICE);

use JeyKeu\Notify\Session\NativeSession;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-12 at 02:28:36.
 */
class SessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Notify
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object          = new NativeSession();
        $appSessKey            = 'jeykeu_notify';
        $key                   = 'testKey';
        $value                 = 'testValue';
        $appSessData           = (object) array($key => $value);
        $_SESSION[$appSessKey] = serialize($appSessData);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->object);
        unset($_SESSION);
    }

    /**
     * @covers NativeSession::set
     * @return array
     */
    public function testSet()
    {
        $key      = 'testKey';
        $value    = 'testValue';
        $this->object->set($key, $value);
        $assert   = $this->object->get($key);
        $expected = 'testValue';
        $this->assertEquals($expected, $assert);
        return array('key' => $key, 'value' => $expected);
    }

    /**
     * @covers NativeSession::get
     * @depends testSet
     */
    public function testGet(array $put)
    {
        $testKey   = $put['key'];
        $testValue = $put['value'];
        $expected  = $this->object->get($testKey);
        $this->assertEquals($expected, $testValue);
    }

    /**
     * @covers JeyKeu\Notify\Session\NativeSession::remove
     * @depends testSet
     */
    public function testRemove(array $put)
    {
        $testKey = $put['key'];
        $this->object->remove($testKey);
        $this->assertEmpty($_SESSION[$testKey]);
    }
}
